services:
  - type: web
    name: stockvibes
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    envVars:
      - key: FINNHUB_API_KEY
        value: your_api_key_here  # You can also set this via the Render dashboard
